#!/bin/bash

set -e

CHECK_PATH=$1'/'

if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    # This is PR
    echo "Checking changes since ${TRAVIS_COMMIT_RANGE} against ${CHECK_PATH}"
    GITDIFF=`git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep ${CHECK_PATH} | tr -d '[:space:]'`
    if [ "$GITDIFF" == "" ]; then
        echo "No code changes, skipped script"
        exit 0
    fi
    "${@:2}"
else
  echo "Not a PR, running the script"
  "${@:2}"
fi
